services:
  - type: web
    name: screenshot-service
    env: node
    plan: free
    region: oregon
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
    startCommand: "npm start"
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false" # Để Puppeteer tải Chromium nếu cần
